apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
#  params:
#    - name: repo-url
#      type: string
#      description: the git repository URL to clone from.
#    - name: revision
#      type: string
#      description: the git revision to clone.
#    - name: image
#      description: reference of the image to build
  workspaces:
    - name: shared-workspace
      description: This workspace will receive the cloned git repo and be passed to the next Task.
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/fouadh/springboot-sample-app.git
#          value: \$(params.repo-url)
        - name: revision
          value: master
#          value: \$(params.revision)
        - name: deleteExisting
          value: "true"
    - name: build-app
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: GOALS
          value: [ "package" ]
#    - name: build-image
#      taskRef:
#        name: kaniko
#      runAfter:
#        - build-app
#      workspaces:
#        - name: source
#          workspace: shared-workspace
#      params:
#        - name: IMAGE
#          value: $(params.image)
